# Generated by Django 4.0.3 on 2022-04-19 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Work', '0003_alter_attendancemaster_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancemaster',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='related_attendance_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Attendance created by user name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancemaster',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='related_attendance_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Attendance updated by user name'),
            preserve_default=False,
        ),
    ]
