# Generated by Django 4.0.3 on 2022-04-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0006_rename_day_attendancemaster_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancemaster',
            name='month',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancemaster',
            name='year',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
    ]
