# Generated by Django 4.0.3 on 2022-04-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0007_attendancemaster_month_attendancemaster_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancemaster',
            name='date',
        ),
        migrations.AddField(
            model_name='attendancemaster',
            name='day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
