# Generated by Django 4.0.3 on 2022-05-09 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmaster',
            old_name='deleted',
            new_name='is_deleted',
        ),
    ]
