# Generated by Django 4.0.3 on 2022-04-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='blogTitle',
        ),
        migrations.AddField(
            model_name='master',
            name='postTitle',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
