# Generated by Django 4.0.3 on 2022-05-10 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_rename_deleted_blogmaster_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmaster',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='blogmaster',
            name='updated_by',
        ),
    ]
