# Generated by Django 4.0.3 on 2022-04-12 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0002_alter_comment_user_alter_like_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Blog',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='Blog',
            new_name='blog',
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
