# Generated by Django 4.0.3 on 2022-04-15 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_remove_master_blogtitle_master_posttitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master',
            old_name='description',
            new_name='postDescription',
        ),
    ]
