# Generated by Django 4.0.3 on 2022-05-10 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
        ('Blog', '0003_remove_blogmaster_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='BlogComment',
        ),
        migrations.RenameModel(
            old_name='Like',
            new_name='BlogLike',
        ),
        migrations.AlterModelTable(
            name='blogcomment',
            table='blog_comment',
        ),
        migrations.AlterModelTable(
            name='bloglike',
            table='blog_like',
        ),
    ]
