# Generated by Django 4.0.3 on 2022-04-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_rename_description_master_postdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
    ]
