# Generated by Django 4.0.3 on 2022-04-14 10:07

import Blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0004_like_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='comment_by',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='like_by',
        ),
        migrations.RemoveField(
            model_name='like',
            name='likedAt',
        ),
        migrations.AddField(
            model_name='like',
            name='liked_at',
            field=models.DateTimeField(auto_now_add=True, default="2022-04-13 13:37:25.564768"),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blogTitle', models.CharField(max_length=50)),
                ('postImage', models.ImageField(null=True, upload_to=Blog.models.get_file_path)),
                ('description', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.master'),
        ),
        migrations.AlterField(
            model_name='like',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.master'),
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
