# Generated by Django 4.0.3 on 2022-05-10 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_rename_comment_blogcomment_rename_like_bloglike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comment', to='Blog.blogmaster'),
        ),
        migrations.AlterField(
            model_name='bloglike',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_like', to='Blog.blogmaster'),
        ),
    ]
