# Generated by Django 4.0.3 on 2022-04-30 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_master_deleted'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comment_master',
        ),
        migrations.AlterModelTable(
            name='like',
            table='like_master',
        ),
        migrations.AlterModelTable(
            name='master',
            table='blog_master',
        ),
    ]
