# Generated by Django 4.0.3 on 2022-05-09 10:36

from django.db import migrations, models
import django.db.models.deletion
from Auth.models import insert_group_data


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=800)),
                ('is_active', models.IntegerField(default=0)),
                ('last_login', models.DateTimeField(null=True)),
                ('is_deleted', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'auth_master',
            },
        ),
        migrations.CreateModel(
            name='GroupMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('permission', models.IntegerField()),
            ],
            options={
                'db_table': 'group_master',
            },
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=800)),
                ('created_at', models.DateTimeField()),
                ('user_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token_user', to='Auth.authmaster')),
            ],
            options={
                'db_table': 'bms_auth_session',
            },
        ),
        migrations.RunPython(insert_group_data),
    ]
