# Generated by Django 4.0.3 on 2022-05-07 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=800)),
                ('created_time', models.IntegerField(blank=True, null=True)),
                ('user_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token_user', to='Auth.authmaster')),
            ],
            options={
                'db_table': 'bms_auth_session',
            },
        ),
    ]
