# Generated by Django 4.0.3 on 2022-05-09 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='created_by',
        ),
    ]
