# Generated by Django 4.0.3 on 2022-05-07 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BmsSession',
        ),
    ]
