# Generated by Django 4.0.2 on 2022-03-06 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dateOfJoining',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='jobType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.jobtype'),
        ),
        migrations.AlterField(
            model_name='user',
            name='jonTittle',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mNo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.position'),
        ),
        migrations.AlterField(
            model_name='user',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.shift'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='workTye',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.worktype'),
        ),
    ]
