# Generated by Django 4.0.3 on 2022-05-09 11:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_remove_usergroup_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 9, 11, 21, 0, 90104, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
