# Generated by Django 4.0.3 on 2022-04-30 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_bmssession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobTypeMaster',
        ),
        migrations.DeleteModel(
            name='RoleMaster',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userposition',
            name='position',
        ),
        migrations.RemoveField(
            model_name='userposition',
            name='user',
        ),
        migrations.DeleteModel(
            name='WorkTypeMaster',
        ),
        migrations.AlterModelTable(
            name='bmssession',
            table='bms_session_master',
        ),
        migrations.AlterModelTable(
            name='departmentmaster',
            table='department_master',
        ),
        migrations.AlterModelTable(
            name='shiftmaster',
            table='shift_master',
        ),
        migrations.AlterModelTable(
            name='usermaster',
            table='user_master',
        ),
        migrations.AlterModelTable(
            name='userpermission',
            table='user_permission',
        ),
        migrations.DeleteModel(
            name='GroupMaster',
        ),
        migrations.DeleteModel(
            name='PositionMaster',
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
        migrations.DeleteModel(
            name='UserPosition',
        ),
    ]
