# Generated by Django 4.0.3 on 2022-05-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_usergroup_created_at_alter_usermaster_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='is_deleted',
            field=models.IntegerField(default=0),
        ),
    ]
