# Generated by Django 4.0.3 on 2022-04-03 15:28

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('mNo', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(null=True, upload_to=User.models.get_file_path)),
                ('address', models.CharField(max_length=250, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('empNo', models.IntegerField()),
                ('about', models.CharField(max_length=255, null=True)),
                ('birthDate', models.DateField(null=True)),
                ('dateOfJoining', models.DateField(null=True)),
                ('jonTittle', models.CharField(max_length=50, null=True)),
                ('updatedAt', models.DateField(null=True)),
                ('createdAt', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Department',
            new_name='DepartmentMaster',
        ),
        migrations.RenameModel(
            old_name='JobType',
            new_name='JobTypeMaster',
        ),
        migrations.RenameModel(
            old_name='Position',
            new_name='PositionMaster',
        ),
        migrations.RenameModel(
            old_name='Shift',
            new_name='ShiftMaster',
        ),
        migrations.RenameModel(
            old_name='WorkType',
            new_name='WorkTypeMaster',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='jobType',
        ),
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='user',
            name='workTye',
        ),
    ]
