# Generated by Django 4.0.3 on 2022-04-04 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_delete_user_userposition_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userposition',
            name='position',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='User.positionmaster'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userposition',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.rolemaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.usermaster')),
            ],
        ),
    ]
