# Generated by Django 4.0.3 on 2022-04-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_groupmaster_permissionmaster_usergroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionmaster',
            name='permission',
            field=models.IntegerField(default=4),
        ),
    ]
