# Generated by Django 4.0.3 on 2022-04-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_alter_permissionmaster_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='permission',
            field=models.IntegerField(default=4),
        ),
        migrations.DeleteModel(
            name='PermissionMaster',
        ),
    ]
