# Generated by Django 4.0.3 on 2022-05-12 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0002_userdepartment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdepartment',
            table='user_department',
        ),
    ]
