# Generated by Django 4.0.3 on 2022-05-12 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0003_alter_userdepartment_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDepartment',
        ),
    ]
